"""US Compliance Templates: I-9, E-Verify, MSA (Master Service Agreement).

Generates compliance documents for US-based placements.
"""

from __future__ import annotations

from datetime import UTC, datetime


def generate_i9_section1(
    employee_name: str,
    address: str,
    date_of_birth: str,
    ssn_last4: str,
    phone: str,
    citizenship_status: str,
    alien_registration_number: str | None = None,
    uscis_number: str | None = None,
    i94_number: str | None = None,
    passport_country: str | None = None,
    passport_number: str | None = None,
    work_authorization_expiry: str | None = None,
) -> dict[str, str]:
    """Generate I-9 Section 1 content (Employee Information and Attestation)."""
    html = f"""
    <html><body style="font-family: Arial, sans-serif; max-width: 700px; margin: 0 auto; padding: 20px;">
    <div style="text-align: center; border: 2px solid #000; padding: 10px; margin-bottom: 20px;">
        <h2 style="margin: 0;">Form I-9</h2>
        <p style="margin: 5px 0;">Employment Eligibility Verification</p>
        <p style="margin: 5px 0; font-size: 11px;">Department of Homeland Security</p>
    </div>
    <h3 style="background: #f3f4f6; padding: 8px;">Section 1. Employee Information and Attestation</h3>
    <table style="width: 100%; border-collapse: collapse;">
        <tr><td style="padding: 6px; border: 1px solid #ccc; width: 40%;">1. Employee Name (Last, First, Middle)</td><td style="padding: 6px; border: 1px solid #ccc;">{employee_name}</td></tr>
        <tr><td style="padding: 6px; border: 1px solid #ccc;">2. Address (Street, Apt#, City, State, ZIP)</td><td style="padding: 6px; border: 1px solid #ccc;">{address}</td></tr>
        <tr><td style="padding: 6px; border: 1px solid #ccc;">3. Date of Birth</td><td style="padding: 6px; border: 1px solid #ccc;">{date_of_birth}</td></tr>
        <tr><td style="padding: 6px; border: 1px solid #ccc;">4. U.S. Social Security Number</td><td style="padding: 6px; border: 1px solid #ccc;">***-**-{ssn_last4}</td></tr>
        <tr><td style="padding: 6px; border: 1px solid #ccc;">5. Employee's Email Address</td><td style="padding: 6px; border: 1px solid #ccc;">{phone}</td></tr>
        <tr><td style="padding: 6px; border: 1px solid #ccc;">6. Phone Number</td><td style="padding: 6px; border: 1px solid #ccc;">{phone}</td></tr>
    </table>
    <h4>Citizenship/Immigration Status</h4>
    <ul>
        <li>{'&#9745;' if citizenship_status == 'us_citizen' else '&#9744;'} 1. A citizen of the United States</li>
        <li>{'&#9745;' if citizenship_status == 'non_citizen_national' else '&#9744;'} 2. A noncitizen national of the United States</li>
        <li>{'&#9745;' if citizenship_status == 'lawful_permanent' else '&#9744;'} 3. A lawful permanent resident</li>
        <li>{'&#9745;' if citizenship_status == 'authorized_alien' else '&#9744;'} 4. A noncitizen authorized to work</li>
    </ul>
    {"<p><strong>Alien Registration Number:</strong> " + (alien_registration_number or "N/A") + "</p>" if alien_registration_number else ""}
    {"<p><strong>USCIS Number:</strong> " + (uscis_number or "N/A") + "</p>" if uscis_number else ""}
    {"<p><strong>I-94 Number:</strong> " + (i94_number or "N/A") + "</p>" if i94_number else ""}
    {"<p><strong>Passport:</strong> " + (passport_country or "") + " " + (passport_number or "N/A") + "</p>" if passport_number else ""}
    {"<p><strong>Work Authorization Expiry:</strong> " + work_authorization_expiry + "</p>" if work_authorization_expiry else ""}
    <br/><p style="font-size: 11px; color: #666;">Generated by ORCAI on {datetime.now(UTC).strftime('%B %d, %Y')}</p>
    </body></html>
    """

    text = (
        f"Form I-9 - Employment Eligibility Verification\n"
        f"{'=' * 50}\n\n"
        f"Section 1. Employee Information and Attestation\n\n"
        f"1. Employee Name: {employee_name}\n"
        f"2. Address: {address}\n"
        f"3. Date of Birth: {date_of_birth}\n"
        f"4. SSN (last 4): {ssn_last4}\n"
        f"5. Phone: {phone}\n\n"
        f"Citizenship Status: {citizenship_status}\n"
        f"{'Alien Reg #: ' + (alien_registration_number or 'N/A') if alien_registration_number else ''}\n"
    )

    return {"html": html, "text": text, "title": f"I-9 Section 1 - {employee_name}"}


def generate_everify_request(
    employee_name: str,
    employer_name: str,
    employer_ein: str,
    i9_date: str,
) -> dict[str, str]:
    """Generate E-Verify case creation request content."""
    html = f"""
    <html><body style="font-family: Arial, sans-serif; max-width: 700px; margin: 0 auto; padding: 20px;">
    <div style="text-align: center; border: 2px solid #000; padding: 10px; margin-bottom: 20px;">
        <h2 style="margin: 0;">E-Verify Case Creation</h2>
        <p style="margin: 5px 0; font-size: 11px;">Employment Eligibility Verification Program</p>
    </div>
    <table style="width: 100%; border-collapse: collapse;">
        <tr><td style="padding: 6px; border: 1px solid #ccc; width: 45%; font-weight: bold;">Employer Name</td><td style="padding: 6px; border: 1px solid #ccc;">{employer_name}</td></tr>
        <tr><td style="padding: 6px; border: 1px solid #ccc; font-weight: bold;">Employer EIN</td><td style="padding: 6px; border: 1px solid #ccc;">{employer_ein}</td></tr>
        <tr><td style="padding: 6px; border: 1px solid #ccc; font-weight: bold;">Employee Name</td><td style="padding: 6px; border: 1px solid #ccc;">{employee_name}</td></tr>
        <tr><td style="padding: 6px; border: 1px solid #ccc; font-weight: bold;">I-9 Completion Date</td><td style="padding: 6px; border: 1px solid #ccc;">{i9_date}</td></tr>
        <tr><td style="padding: 6px; border: 1px solid #ccc; font-weight: bold;">Case Status</td><td style="padding: 6px; border: 1px solid #ccc;">Pending E-Verify Case Creation</td></tr>
    </table>
    <p style="margin-top: 20px;">Submit this information via the E-Verify employer portal at <a href="https://www.e-verify.gov">e-verify.gov</a>.</p>
    <p style="font-size: 11px; color: #666;">Generated by ORCAI on {datetime.now(UTC).strftime('%B %d, %Y')}</p>
    </body></html>
    """
    return {
        "html": html,
        "text": f"E-Verify Case Creation\nEmployer: {employer_name}\nEIN: {employer_ein}\nEmployee: {employee_name}\nI-9 Date: {i9_date}",
        "title": f"E-Verify - {employee_name}",
    }


def generate_msa(
    client_name: str,
    vendor_name: str,
    effective_date: str,
    rate_type: str = "hourly",
    rate_amount: str | None = None,
    payment_terms: str = "Net 30",
    term_length: str = "12 months",
    governing_law: str = "State of California",
) -> dict[str, str]:
    """Generate a Master Service Agreement (MSA) template."""
    html = f"""
    <html><body style="font-family: Georgia, serif; max-width: 700px; margin: 0 auto; padding: 40px;">
    <div style="text-align: center; border-bottom: 2px solid #1f2937; padding-bottom: 20px; margin-bottom: 30px;">
        <h1 style="color: #1f2937; margin: 0;">Master Service Agreement</h1>
        <p style="color: #6b7280; font-size: 12px;">BETWEEN {vendor_name.upper()} AND {client_name.upper()}</p>
    </div>
    <p><strong>Effective Date:</strong> {effective_date}</p>
    <p><strong>Party A (Client):</strong> {client_name}</p>
    <p><strong>Party B (Vendor/Agency):</strong> {vendor_name}</p>

    <h3>1. Scope of Services</h3>
    <p>Party B shall provide recruitment and staffing services to Party A, including but not limited to candidate sourcing, screening, interview coordination, and placement management.</p>

    <h3>2. Rate Structure</h3>
    <p>Compensation shall be on a <strong>{rate_type}</strong> basis.{' Rate: ' + rate_amount + '.' if rate_amount else ''} Payment terms: <strong>{payment_terms}</strong>.</p>

    <h3>3. Term and Termination</h3>
    <p>This Agreement shall be effective for <strong>{term_length}</strong> from the Effective Date. Either party may terminate with 30 days written notice.</p>

    <h3>4. Confidentiality</h3>
    <p>Both parties agree to maintain the confidentiality of all proprietary information shared during the term of this Agreement.</p>

    <h3>5. Compliance</h3>
    <p>Party B shall comply with all applicable federal, state, and local employment laws, including but not limited to EEO, DPDPA (India), and I-9/E-Verify requirements (US).</p>

    <h3>6. Indemnification</h3>
    <p>Each party shall indemnify the other against claims arising from their own negligence or willful misconduct.</p>

    <h3>7. Governing Law</h3>
    <p>This Agreement shall be governed by the laws of <strong>{governing_law}</strong>.</p>

    <br/>
    <table style="width: 100%; border-collapse: collapse;">
        <tr>
            <td style="width: 50%; padding: 20px;">
                <div style="border-top: 1px solid #ccc; width: 200px; padding-top: 5px;">
                    <p style="font-size: 11px; color: #666;">{vendor_name}</p>
                    <p style="font-size: 11px; color: #666;">Date: ________________</p>
                </div>
            </td>
            <td style="width: 50%; padding: 20px;">
                <div style="border-top: 1px solid #ccc; width: 200px; padding-top: 5px;">
                    <p style="font-size: 11px; color: #666;">{client_name}</p>
                    <p style="font-size: 11px; color: #666;">Date: ________________</p>
                </div>
            </td>
        </tr>
    </table>
    <p style="font-size: 10px; color: #999; margin-top: 30px;">Generated by ORCAI on {datetime.now(UTC).strftime('%B %d, %Y')} — review with legal counsel before use.</p>
    </body></html>
    """

    text = (
        f"Master Service Agreement\n"
        f"{'=' * 40}\n\n"
        f"Effective Date: {effective_date}\n"
        f"Client: {client_name}\n"
        f"Vendor: {vendor_name}\n\n"
        f"1. SCOPE OF SERVICES\nParty B shall provide recruitment and staffing services.\n\n"
        f"2. RATE STRUCTURE\nRate type: {rate_type}.{' Rate: ' + rate_amount + '.' if rate_amount else ''}\nPayment terms: {payment_terms}.\n\n"
        f"3. TERM\n{term_length}. 30 days notice for termination.\n\n"
        f"4. CONFIDENTIALITY\nBoth parties maintain confidentiality.\n\n"
        f"5. COMPLIANCE\nAll applicable employment laws.\n\n"
        f"6. GOVERNING LAW\n{governing_law}\n"
    )

    return {"html": html, "text": text, "title": f"MSA - {vendor_name} & {client_name}"}
