"""add_interview_email_note_tag_notification_settings_models

Revision ID: 056989210a87
Revises: b3a1d2f4c9e8
Create Date: 2026-09-20 15:26:01.140967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '056989210a87'
down_revision: Union[str, Sequence[str], None] = 'b3a1d2f4c9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
