"""add client portal and campaigns

Revision ID: 78a9bd7d41cf
Revises: 8f44ae1b3803
Create Date: 2026-09-20 16:14:19.048152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78a9bd7d41cf'
down_revision: Union[str, Sequence[str], None] = '8f44ae1b3803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
