"""add_scorecard_models

Revision ID: 8f44ae1b3803
Revises: 3729874fd204
Create Date: 2026-09-20 16:11:51.316884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f44ae1b3803'
down_revision: Union[str, Sequence[str], None] = '3729874fd204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('seeker_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('offered_salary', sa.Float(), nullable=True),
    sa.Column('offered_currency', sa.String(length=8), nullable=False),
    sa.Column('start_date', sa.String(length=30), nullable=True),
    sa.Column('offer_expiry', sa.String(length=30), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['seeker_id'], ['seekers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_agency_id'), 'offers', ['agency_id'], unique=False)
    op.create_index(op.f('ix_offers_contract_id'), 'offers', ['contract_id'], unique=False)
    op.create_index(op.f('ix_offers_match_id'), 'offers', ['match_id'], unique=False)
    op.create_index(op.f('ix_offers_seeker_id'), 'offers', ['seeker_id'], unique=False)
    op.create_table('offer_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_approvals_agency_id'), 'offer_approvals', ['agency_id'], unique=False)
    op.create_index(op.f('ix_offer_approvals_approver_id'), 'offer_approvals', ['approver_id'], unique=False)
    op.create_index(op.f('ix_offer_approvals_offer_id'), 'offer_approvals', ['offer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offer_approvals_offer_id'), table_name='offer_approvals')
    op.drop_index(op.f('ix_offer_approvals_approver_id'), table_name='offer_approvals')
    op.drop_index(op.f('ix_offer_approvals_agency_id'), table_name='offer_approvals')
    op.drop_table('offer_approvals')
    op.drop_index(op.f('ix_offers_seeker_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_match_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_contract_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_agency_id'), table_name='offers')
    op.drop_table('offers')
    # ### end Alembic commands ###
